/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as PlacementRouteImport } from './routes/placement'
import { Route as ItTrainingRouteImport } from './routes/it-training'
import { Route as CorporateTrainingRouteImport } from './routes/corporate-training'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AviationRouteImport } from './routes/aviation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementRoute = PlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const ItTrainingRoute = ItTrainingRouteImport.update({
  id: '/it-training',
  path: '/it-training',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateTrainingRoute = CorporateTrainingRouteImport.update({
  id: '/corporate-training',
  path: '/corporate-training',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AviationRoute = AviationRouteImport.update({
  id: '/aviation',
  path: '/aviation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aviation': typeof AviationRoute
  '/contact': typeof ContactRoute
  '/corporate-training': typeof CorporateTrainingRoute
  '/it-training': typeof ItTrainingRoute
  '/placement': typeof PlacementRoute
  '/skills': typeof SkillsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aviation': typeof AviationRoute
  '/contact': typeof ContactRoute
  '/corporate-training': typeof CorporateTrainingRoute
  '/it-training': typeof ItTrainingRoute
  '/placement': typeof PlacementRoute
  '/skills': typeof SkillsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aviation': typeof AviationRoute
  '/contact': typeof ContactRoute
  '/corporate-training': typeof CorporateTrainingRoute
  '/it-training': typeof ItTrainingRoute
  '/placement': typeof PlacementRoute
  '/skills': typeof SkillsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/aviation'
    | '/contact'
    | '/corporate-training'
    | '/it-training'
    | '/placement'
    | '/skills'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/aviation'
    | '/contact'
    | '/corporate-training'
    | '/it-training'
    | '/placement'
    | '/skills'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/aviation'
    | '/contact'
    | '/corporate-training'
    | '/it-training'
    | '/placement'
    | '/skills'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AviationRoute: typeof AviationRoute
  ContactRoute: typeof ContactRoute
  CorporateTrainingRoute: typeof CorporateTrainingRoute
  ItTrainingRoute: typeof ItTrainingRoute
  PlacementRoute: typeof PlacementRoute
  SkillsRoute: typeof SkillsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement': {
      id: '/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof PlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it-training': {
      id: '/it-training'
      path: '/it-training'
      fullPath: '/it-training'
      preLoaderRoute: typeof ItTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-training': {
      id: '/corporate-training'
      path: '/corporate-training'
      fullPath: '/corporate-training'
      preLoaderRoute: typeof CorporateTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviation': {
      id: '/aviation'
      path: '/aviation'
      fullPath: '/aviation'
      preLoaderRoute: typeof AviationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AviationRoute: AviationRoute,
  ContactRoute: ContactRoute,
  CorporateTrainingRoute: CorporateTrainingRoute,
  ItTrainingRoute: ItTrainingRoute,
  PlacementRoute: PlacementRoute,
  SkillsRoute: SkillsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
